### ISSUE TITLE
No MYSQL_PASS in logs

### ISSUE THREAD

**Issue by tallpauley** [RedpointGames/phabricator#47]
Can there be an environment variable option to `set +x` whenever **MYSQL_PASS**  is referenced in `10-boot-conf`? Having **MYSQL_PASS** in the logs is a security vulnerability. I can do this and submit a pull request if you'd prefer.

(btw, thanks for making this container, it's the best I'm aware of. built-in lets encrypt is great)

**Comment by hach-que** [comment]
Sure, feel free to send through a PR.

**Comment by hach-que** [comment]
This bug should be fixed a version that is currently undergoing testing.

**Comment by hach-que** [comment]
This is now fixed in the latest version.
