### ISSUE TITLE
Missing diffusion.ssh-user

### ISSUE THREAD

**Issue by michalciolek** [RedpointGames/phabricator#64]
Your script does not set configurations for `diffusion.ssh-user` and all repo URL are wrong. I get
`git clone ssh://{IP/DOMAIN}/diffusion/1/testrepo.git` and when I run this command I get:
```
Cloning into 'testrepo'...
Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Correct URL is: `git clone ssh://git@{IP/DOMAIN}/diffusion/1/testrepo.git`

You should add to `10-boot-conf` script:
`sudo -u "$PHABRICATOR_VCS_USER" ./bin/config set diffusion.ssh-user "$PHABRICATOR_VCS_USER"`

**Comment by hach-que** [comment]
That setting used to be driven by `phd.user` (as a side effect to also specifying the user for daemons).  My guess is that a recent update in Phabricator removed this.

I won't get to this for a week or so.  Feel free to send a PR if you need it sooner.

**Comment by hach-que** [comment]
This bug should be fixed a version that is currently undergoing testing.

**Comment by hach-que** [comment]
This is now fixed in the latest version.
