### ISSUE TITLE
MySQL error despite using PHABRICATOR_STORAGE_TYPE=disk

### ISSUE THREAD

**Issue by zommuter** [RedpointGames/phabricator#68]
When I run

    docker run -p 8080:80 -p 8043:443 -p 8022:22 \
        -e PHABRICATOR_HOST=my.host \
        -e PHABRICATOR_STORAGE_TYPE=disk \
        -e PHABRICATOR_STORAGE_PATH=//files -v phabricator-storage://files \
        -e PHABRICATOR_REPOSITORY_PATH=//repos -v phabricator-repos://repos \
        --rm --name phabricator redpointgames/phabricator

I still get an error about a lack of MySQL:

```
mysqlcheck: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysql/mysql.sock' (2 "No such file or directory") when trying to connect
+ /srv/phabricator/phabricator/bin/storage upgrade --force
MySQL Credentials Not Configured

Unable to connect to MySQL using the configured credentials. You must
configure standard credentials before you can upgrade storage. Run these
commands to set up credentials:

  phabricator/ $ ./bin/config set mysql.host __host__
  phabricator/ $ ./bin/config set mysql.user __username__
  phabricator/ $ ./bin/config set mysql.pass __password__

These standard credentials are separate from any administrative credentials
provided to this command with __--user__ or __--password__, and must be
configured correctly before you can proceed.
```

So either I misunderstood [BASIC-CONFIG](https://github.com/RedpointGames/phabricator/blob/master/BASIC-CONFIG.md#configuring-phabricator) or this is a bug...

**Comment by hach-que** [comment]
You still need MySQL. That flag just configures where files are stored.

**Comment by zommuter** [comment]
Thanks, I definitely misunderstood that. https://secure.phabricator.com/book/phabricator/article/configuring_file_storage/ sheds some light on this.
