### ISSUE TITLE
stable branch

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [RedpointGames/phabricator#69]
Hi there,

i would propose to create docker images of phabricator which are based on the stable branch of phabricator. The github phabricator code provides such a stable branch. So please create also stable tagged images based on this branch. This would be a better choice for production use of your container.
https://github.com/phacility/phabricator/tree/stable

best,
Christian

**Comment by hach-que** [comment]
You can actually already do this by overriding the branches for the repositories with environment variables, as outlined here: https://github.com/RedpointGames/phabricator/blob/master/ADVANCED-CONFIG.md#using-different-source-repositories

Note that you don't need to pass the URIs if you want to use the default repositories.  You can just set the `OVERRIDE_*_BRANCH` environment variables to set them to `origin/stable`.

**Comment by cguentherTUChemnitz** [comment]
How do i use the stable branch without updating during startup? I want to run a phabricator version which is not changed during container restart, for backup purposes. When i want to upgrade the container version i rebuild the image. But setting the

```
OVERRIDE_PHABRICATOR_BRANCH=stable
OVERRIDE_ARCANIST_BRANCH=stable
OVERRIDE_LIBPHUTIL_BRANCH=stable
```

variables enables automatically the update on startup. So how do i get a stable branch phabricator build only during docker image build and not updating during restart?

**Comment by hach-que** [comment]
Are you using the image baking mechanism? If so, it shouldn't be running `git pull` again, as that is done in `10-boot-conf` and that has:

```
if [ -f /baked ]; then
  exit 0
fi
```

at the top; which means once the image is baked it won't run it again.
