### ISSUE TITLE
Deleting Repository

### ISSUE THREAD

**Issue by simPod** [RedpointGames/phabricator#70]
When trying to delete repository in your docker image, it says to use this command:

![image](https://cloud.githubusercontent.com/assets/327717/23339541/781ac7dc-fc25-11e6-99f0-0a10006cd171.png)

However, when listing the bin directory `ls`, there's no script with name `remove`

![image](https://cloud.githubusercontent.com/assets/327717/23339554/a41b1846-fc25-11e6-9ee2-429c0a69c341.png)

How can I delete the repository?

**Comment by hach-que** [comment]
This script is located under `/srv/phabricator/phabricator`.  Thus you can run it with:

```
/srv/phabricator/phabricator/bin/remove destroy ...
```

**Comment by simPod** [comment]
Wow, such fast reponse. It works, thanks!
