### ISSUE TITLE
Docker images in new location not updated?

### ISSUE THREAD

**Issue by therealprof** [RedpointGames/phabricator#73]
Hi guys,

I followed your instructions on the docker hub:
```
This repository has been recently moved to RedpointGames/phabricator and the Docker image to use is now redpointgames/phabricator. hachque/phabricator will be kept in sync with redpointgames/phabricator for the foreseeable future, so you don't need to update your configuration immediately.
```

and used the *redpointgames/phabricator* image, however unlike the *hachque/phabricator* image (latest
603 MB 41 minutes ago) the new one doesn't seem to receive any updates (latest 601 MB a month ago)?

NB: The new github repo headline also still points to the supposedly outdated image in the docker hub.

**Comment by hach-que** [comment]
Huh, that's weird.  Both Docker hub images should be linked to this repo, so it's quite possible there's something weird going on with how Docker detects updates in GitHub.

I'll manually kick off a build on `redpointgames/phabricator` until I get a chance to look at what's going on in a few days.

**Comment by therealprof** [comment]
Hah! I see you corrected the link in the headline, however the docker hub seems to be case sensitive so it doesn't work, should be https://hub.docker.com/r/redpointgames/phabricator/ instead. ;)

**Comment by hach-que** [comment]
Oh thanks for pointing that out! Why their URLs are case sensitive when it normalises all the usernames during registration to lowercase is beyond me...

**Comment by therealprof** [comment]
Any news regarding the updates?

**Comment by hach-que** [comment]
Thanks for reminding me to look into this.

It turns out the `hachque/phabricator` image was linked to `hachque/systemd-none`, while the `redpointgames/phabricator` was not.  `hachque/systemd-none` has a build triggered every hour.

I've updated `redpointgames/phabricator` to also rebuild like `hachque/phabricator`, which should resolve the issue.
