### ISSUE TITLE
Rebuild image on Docker hub

### ISSUE THREAD

**Issue by michelkaeser** [RedpointGames/phabricator#83]
Hi guys

Could you maybe trigger a rebuild on the Docker hub so it builds with the latest Phabricator source? The current one seems to have a bug (trying to navigate in Diffusion shows "Undefined variable: view").

Since it is 15 days old I hope this would be fixed if rebuild. Thanks!

**Comment by hach-que** [comment]
Unfortunately we can't as the distro this image is based on has been EOL'd. We have to change the base image to Ubuntu at some point in the future.

In the meantime you can use the environment variables to make it update the Phabricator source code on startup.
