### ISSUE TITLE
email address add error

### ISSUE THREAD

**Issue by liujiaxian** [RedpointGames/phabricator#85]
Settings > Email Addresses > add new address

Unhandled Exception ("AphrontQueryException")	
#1055: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'phabricator_system.system_actionlog.actorIdentity' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by hach-que** [comment]
It sounds like your MySQL instance is in the wrong SQL mode, which is preventing things from working.

As far as I'm aware, `sql_mode` should be set to `STRICT_ALL_TABLES` not `ONLY_FULL_GROUP_BY`.
