### ISSUE TITLE
Can't enable opcache support

### ISSUE THREAD

**Issue by Alexhha** [RedpointGames/phabricator#86]
Hello,

I'm using the following version of 

```
Installed Versions
phabricator 	f7f3dd5b20848c221e16bc34b3ce61ddbdbdde94 (Fri, Oct 27)
arcanist 	0989343a4e0c27357a72b9adcce338e7ec497965 (Fri, Oct 20)
phutil 		95c065963998fa4dd8aa077dea737a71d3c5a674 (Mon, Oct 23)
diff 		3.3 at /usr/bin/diff
git 		2.13.6 at /usr/bin/git
hg 		4.3.1 at /usr/bin/hg
pygmentize 	2.2.0 at /usr/bin/pygmentize
svn 		1.9.7 at /usr/bin/svn
```

Under Config -> Setup -> Setup issue it shows me a warning - "**PHP Extension "APCu" Not Installed**". Is it possible to integrate it with opcache instead of APCu? As I can see the opcache module already installed. Do I need to configure it manually?

**Comment by hach-que** [comment]
This image only supports APCU. You need to enable it as outlined in the environment variable list here: https://github.com/RedpointGames/phabricator/blob/master/ENV-LIST.md
