### ISSUE TITLE
Question git build Phabricator by docker

### ISSUE THREAD

**Issue by victorsheng** [RedpointGames/phabricator#89]
I want import my compay's gitlab Repository by http way,but I can't clone from gitlab
![image](https://user-images.githubusercontent.com/11304150/32884003-ed4762ac-caf3-11e7-9671-1bdafed8a58a.png)
and I add
     --privileged=true \
however, it doesn't work

**Comment by DarthGandalf** [comment]
I had the same issue.
`# chown 2000 /srv/docker/phabricator/repos/` on host fixed it.

**Comment by hach-que** [comment]
Yeah, you'll need to make sure that either the mapped repository volume is world writable (so the Docker instance can write into it), or that it has the correct UID (even if there's no user in the host instance that maps to the UID).

There's nothing actionable here, so I'm going to close this issue.
